### ISSUE TITLE
Reference to missing numpy array

### ISSUE THREAD

**Issue by bartmch** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#1]
There's a file missing. On line 94 in train_detector_se.py you're referencing some file on your local computer:
`luna_data = np.load('/home/LungNodule_DL/detector/luna_folds/luna_fold6.npy')`

Would it be possible to share this file or clarify what this file should be?

Thanks

**Comment by ymli39** [comment]
Thanks for pointing that out, I have uploaded and file and changed the code.

**Comment by MjdMahasneh** [comment]
@bartmch

The paper mentions 10-folds validation (which I presume, also means there is 10-fold training), my question is :

1-how is the 10-fold training done using the training script?
2-are these files (luna_train.npy and luna_test.npy) related to the 10-fold training?
3-how are these files generated?

Looking forward to hearing back from you.
