### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by tonyreina** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#11]
Would it be possible to post a pre-trained model somewhere for this?  I work for Intel and would love to use the pre-trained model to benchmark our inference performance.

Best.
Very respectfully,
-Tony

**Comment by deepkaneria** [comment]
Hey there, 

Can you please share those pre-trained weights, It's already the end of November.

Best.
Very Respectfully

**Comment by ymli39** [comment]
Hi all, Sorry about the delay, I just uploaded the pre-trained weights. I got too many models on my server and we just cleaned all the data this summer, takes me a while to find the correct model weights.
