### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'test_results/se_focal_fold6/detector_177.ckpt'

### ISSUE THREAD

**Issue by caomeishanzhu** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#12]
How can I solve this problem?
FileNotFoundError: [Errno 2] No such file or directory: 'test_results/se_focal_fold6/detector_177.ckpt'.

**Comment by ymli39** [comment]
This is the trained model file name, you could replace this directory with your own trained model.
