### ISSUE TITLE
question about FROCeval. py

### ISSUE THREAD

**Issue by hengliang8** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#13]
I use your trained model, and test it, but the result is far from your result in your exciting  paper.  the detp I set  is [0.3, 0.4, 0.5, 0.6, 0.7]. can you help me? 
wish for your reply

**Comment by hengliang8** [comment]
![froc_predanno0 3](https://user-images.githubusercontent.com/44434361/70293353-5526a100-181b-11ea-9719-1b36264b82f8.png)

This is the result I get

**Comment by ymli39** [comment]
Maybe something wrong with your data name, you could use the one from LUNA16 website to test whether their provided scripts demo works. If it works then test the current results.

**Comment by ymli39** [comment]
I have uploaded my results as reference.

**Comment by hengliang8** [comment]
thank you
