### ISSUE TITLE
Need some clarification on outputs

### ISSUE THREAD

**Issue by shakjm** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#16]
Hi there, I'm trying to replicate your model and I was wondering how are your outputs being used? They're lbb and pbb. I'm guessing lbb is the labels, where as pbb is a feature vector of [x,5]. What are they representing?

Also, is there any way I can generate an image to see where the bounding boxes land? How do I do that and how do the coordinates match with the images that were preprocessed?

**Comment by ymli39** [comment]
The postprocessing code is located in /LIDC_detector/FROCeval.py.
[x,5] represents x,y,z,d, and probability.
You need to convert x,y,z,d to bounding boxes then draw boxes on the images.
Each images are preprocessed based on its own spacing, origin, to convert it back to original coordinate, check /LIDC_detector/FROCeval.py.

**Comment by shakjm** [comment]
Thank you Mr. Li for the clarification.
