### ISSUE TITLE
Issue when training model

### ISSUE THREAD

**Issue by bartmch** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#2]
Hi, I'm getting the following issue (after preprocessing the image). Would it be possible to look into this please?
Also I couldn't find any ways in testing the model, before training it.

![image](https://user-images.githubusercontent.com/10415569/60021312-d5f54480-96a2-11e9-866b-2f3f23bc613a.png)

**Comment by bartmch** [comment]
On line 68: `self.bboxes = np.concatenate(self.bboxes,axis = 0)`. The issue I'm facing is that `self.bboxes = []`.
I'm running this in the training mode by setting the default value of `--test` `default=0` so I can run the training procedure by just typing `python train_detector_se.py`

**Comment by ymli39** [comment]
Are you using same data preprocessing code as I provided?

**Comment by bartmch** [comment]
Hi, yes - after running changing config_training.py and running prepare.py, I get all the preprocessed data in "luna_data" and "preprocess_result_path". I'm running into an empty bboxes error after I run train_detector_se.py in training mode. Thanks!

**Comment by ymli39** [comment]
I did not encounter this problem before. I think you could set a debug point at dataloader line 57 to check whether it loads bounding boxes for each label?
