### ISSUE TITLE
The prediction probability is not in 0-1 range?

### ISSUE THREAD

**Issue by KinaTech** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#21]
Hi, thanks for the wonderful explanation.
When I test your model, I found the prediction probability is not in 0-1 range.
I mean the probability is like 4.5, 18, 21.5. Does these phenomenon normal?
It looks like these are the diameter of the nodules. But how can I get the probabilities? 
I attach an example of output of the model. 
Thanks in advance @ymli39 

       [ -2.97817516, 285.57787803, 285.55532278, 425.68683523,
          9.22237027],
       [ -2.78340006, 285.48476638, 285.41791546, 429.51884933,
          5.54941623],
       [ -2.89723754, 285.46616549, 285.3996337 , 429.56445795,
          9.20982807]])

**Comment by kingjames1155** [comment]
> Hi, thanks for the wonderful explanation. When I test your model, I found the prediction probability is not in 0-1 range. I mean the probability is like 4.5, 18, 21.5. Does these phenomenon normal? It looks like these are the diameter of the nodules. But how can I get the probabilities? I attach an example of output of the model. Thanks in advance @ymli39
> 
> ```
>    [ -2.97817516, 285.57787803, 285.55532278, 425.68683523,
>       9.22237027],
>    [ -2.78340006, 285.48476638, 285.41791546, 429.51884933,
>       5.54941623],
>    [ -2.89723754, 285.46616549, 285.3996337 , 429.56445795,
>       9.20982807]])
> ```


I have encountered the same problem. Have you solved it
