### ISSUE TITLE
Clarification on dependencies

### ISSUE THREAD

**Issue by MjdMahasneh** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#22]
@ymli39 

Could you kindly clarify what are the dependencies to run this project? What versions were used (e.g. Python, PyTorch, CUDA, cuDNN,..etc.) 

This is very helpful for the reproduction of this work.

Many thanks in advance.

**Comment by dinhanhx** [comment]
Please add requirements.txt for Python

**Comment by ymli39** [comment]
Sorry about late response, I used pytorch version of 0.4.1.

**Comment by MjdMahasneh** [comment]
Thank you so much for your response.
