### ISSUE TITLE
Clarification on Converting output bounding boxes to predictions in predanno0.3.csv

### ISSUE THREAD

**Issue by plyh** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#24]
May I ask how are the output bounding box predictions and output labels from testing be translated into input (predanno.csv) for FROC evaluation? Which code does that?

**Comment by ymli39** [comment]
Sorry about late response, the evaluation script is in folder "/LIDC_detector/FROCeval.py".
