### ISSUE TITLE
Documenting code where build network

### ISSUE THREAD

**Issue by dinhanhx** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#26]
Adding comments will help other people to rebuild or deploy easily

**Comment by dinhanhx** [comment]
Reason to close?

**Comment by ymli39** [comment]
Since this thread has been sitting here for a while and I am afraid I could not provide further updates, so I closed this issue together with another one.

**Comment by dinhanhx** [comment]
I see.
