### ISSUE TITLE
problems about froc results

### ISSUE THREAD

**Issue by oliva-cool** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#28]
Hi,  I use your posted the predanno0.3.csv to get the froc values using the script noduleCADEvaluationLUNA16.py with your codes defualt setting, I get the normal results. The froc results printed are as below:
            Senstivity    FPS
            0.68696856 0.125
            0.75847465 0.25
            0.8146588 0.5
            0.8623556 1.0
            0.9020456 2.0
            0.9117384 4.0
            0.9117384 8.0
            mean value: 0.83542573
However, I use your codes train the model with your pretrained model, I get the froc results with same settings are as below:
            Senstivity    FPS
            0.03737833 0.125
            0.100776754 0.25
            0.1428685 0.5
            0.3355601 1.0
            0.7871244 2.0
            0.93348473 4.0
            0.93348473 8.0
            0.46723965
            mean value: 0.45514950166112955 

By the way, I use your luna_train.npy and luna_test.npy do the run and validation, and get the tpr 97.57, tnr 99.53 ,loss 0.0133, classify loss 0.0045, regress loss 0.0020, 0.0019, 0.0024, 0.0025 with total pos 1767, total neg 7068 upon train datasets.

tpr 96.13, tnr 99.99790957, loss 0.0095, classify loss 0.0000, regress loss 0.0015, 0.0021, 0.0026, 0.0033 with total pos 181, total neg 17699714 upon val datasets.

I am confused about the low senstivity with the fps [0.125,0.25,0.5] ,could you give me some advice about the this problem? I will be greatly appreciated about you reply.

**Comment by kingjames1155** [comment]
Hi, I have encountered the same problem as you. The FROC score is relatively low. How do you solve it
