### ISSUE TITLE
Regarding file structure

### ISSUE THREAD

**Issue by yashkarbhari** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#29]
I had a doubt regarding the difference between the folders "Luna_raw" and "Luna_data".

**Comment by ymli39** [comment]
I am not sure what is your quesiton, the definition of each folders is explained in the ReadMe, Luna_data is a temporary folder.

**Comment by yashkarbhari** [comment]
I found the answer to my question. It's fine to close the issue.
