### ISSUE TITLE
Multi class support？

### ISSUE THREAD

**Issue by coolKeen** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#3]
@ymli39  Hi, thanks for sharing your code and paper. I wonder whether it supports multi-class detection when I use luna_detector (not only detect pulmonary nodule).  If not,  how can I modify the code to support multi-class detection?
Thanks in advance!

**Comment by ymli39** [comment]
The original code does not support multi-class detection. In addition to pass the bounding boxes as gt, you could also pass the label and modify the loss function.
