### ISSUE TITLE
请问怎么可视化输出的结果呢（How to visualize the npy files which we have after testing）

### ISSUE THREAD

**Issue by XYX1998** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#31]
How to visualize the pbb.npy files which we have after testing?
Thanks plz

**Comment by ymli39** [comment]
After you generate the excel file you could find all the scan ID with locations (x,y,z) with anchor size (r), then you need to write your own visualization code to visualize the results.
