### ISSUE TITLE
Cannot find CPM (7 Recall Average) Part of your code

### ISSUE THREAD

**Issue by torki-hossein** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#33]
Hi,
Thanks for sharing your codes and thanks for your good paper.
I'm working on LUNA16 challenge as an application of our thesis and I have some ideas to extend all current works on this domain.
I'm using some publicly shared works in this domain but I have some problem in the CPM computation.
I think after calling LunaCADEvaluationScript.py we must to interpolate Fps's (False Positive per Scan) but I found some works mismatch in current reported CPM with my implementation.
I would like to know can you share with me CPM computation of your paper implementation?
I cannot found that part in your repo.
Best regards

**Comment by ymli39** [comment]
If you are asking for mean score of FROC, you could take the average of all 7 scores at different FP rate per scan, and you get 7 scores from the luna evaluation script.
