### ISSUE TITLE
About 'new_nodule.csv'

### ISSUE THREAD

**Issue by fzpr** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#35]
Hi
Can ` new_nodule.csv` be used to locate nodules in each CT scan?

**Comment by ymli39** [comment]
The new_nodule.csv from LIDC dataset follows the same location format as annos.csv from LUNA dataset. The new_nodule.cvs are extracted based on offical LIDC xml script. 

It has been a long time and I do not recall the exact coordinates of those scans but if you could locate nodules for LUNA dataset, then you could locate nodules in LIDC dataset as well.
