### ISSUE TITLE
 from layers import iou ModuleNotFoundError: No module named 'layers'

### ISSUE THREAD

**Issue by aldemirfilho** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#36]
hello, after running the pre-processing of the data, and starting the training, I'm getting the following error:

File "/content/drive/MyDrive/Pibic/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection-master/luna_detector/data_loader.py", line 16, in <module>
    from layers import iou
ModuleNotFoundError: No module named 'layers'

I searched and didn't find much about this library, did it have any updates? Can you give me instructions on how to proceed?

Thanks!

**Comment by ymli39** [comment]
Sorry my bad, the directory should be layers_se.py instead of layers.py.

**Comment by aldemirfilho** [comment]
Thanks!
