### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/train_result/detector_177.ckpt'

### ISSUE THREAD

**Issue by aldemirfilho** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#37]
I saw a similar question already answered regarding the tests, in this case in the training stage, how can I proceed?
FileNotFoundError: [Errno 2] No such file or directory: '/train_result/detector_177.ckpt'

Thanks!

**Comment by ymli39** [comment]
Did you save the model in that directory? If yes then you need to change the model directory  '/train_result/detector_177.ckpt' to the correct name that matches your saved model....
