### ISSUE TITLE
About FROC Score

### ISSUE THREAD

**Issue by kingjames1155** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#41]
Hi,
Thanks for sharing your codes and thanks for your good paper. 
I use the predanno0.3.csv provided by you, and according to luna_ Test.npy has made the corresponding CSV file. I found that the FROC scores of 0.125, 0.25, 0.5 and 0.1 are lower than expected. Do you have any good suggestions? I evaluated the CSV detection file provided by you.

Total number of included nodule annotations: 86
Total number of nodule annotations: 3596
(1000, 10000)
##########################
0.47112617 0.125
0.60532993 0.25
0.74687976 0.5
0.8357665 1.0
0.9013603 2.0
0.9310172 4.0
0.93185717 8.0
0.77476245
0.7691029900332226 16.0

CAD Analysis: predanno0.3
************************************************************

Candidate detection results:
    True positives: 83
    False positives: 1443
    False negatives: 6
    True negatives: 0
    Total number of candidates: 1770
    Total number of nodules: 89
    Ignored candidates on excluded nodules: 230
    Ignored candidates which were double detections on a nodule: 14
    Sensitivity: 0.932584270
    Average number of candidates per scan: 19.450549451

**Comment by ymli39** [comment]
Hi sorry about the late response, I just fixed the bug in the file "noduleCADEvaluationLUNA16.py", I have added fold9 csv for test (/luna_detector/labels/luna_test.csv), you can directly run noduleCADEvaluationLUNA16.py to generate the results. The results should match the one that I uploaded.

update:
The missing nodules in file "nodulesWithoutCandidate_predanno0.3.txt." should be:

237,None,56.58885682,-67.46153204,-77.34666348,3.270466947,-1
612,None,-6.607170093,22.55937329,-143.7929641,9.484890340,-1
612,None,116.8024039,-1.291850522,-197.5054168,4.666322736,-1
612,None,119.2088976,-11.4328236,-208.2932951,6.853377495,-1
612,None,111.5336493,-37.25625083,-238.8281758,5.772283337,-1
612,None,95.99601184,-23.33441995,-157.7220192,4.835148932,-1
