### ISSUE TITLE
About FROC Score

### ISSUE THREAD

**Issue by kacel33** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#42]
Hi,
Thanks for sharing your codes, and thanks for your good paper.
I use 177.ckpt provided by you, and according to luna Test.npy has made the corresponding CSV file and PNG file.
I found that the FROC scores of 0.125, 0.25, 0.5, 1, 2, 4, 8 are lower than paper.
Do you have any suggestions?

I changed your code and show 64 false positive per scan, the result shows 0.93 sensitivity.
And I trained 150 epochs, the result was similar. 

![image](https://user-images.githubusercontent.com/60708119/212586347-1352a349-9297-4ae4-b114-f846fd4a4c07.png)

************************************************************
CAD Analysis: predanno0.3
************************************************************

Candidate detection results:
    True positives: 80
    False positives: 1423
    False negatives: 6
    True negatives: 0
    Total number of candidates: 1735
    Total number of nodules: 86
    Ignored candidates on excluded nodules: 218
    Ignored candidates which were double detections on a nodule: 14
    Sensitivity: 0.930232558
    Average number of candidates per scan: 19.715909091

**Comment by ymli39** [comment]
Hi sorry about the late response, I just fixed the bug in the file "noduleCADEvaluationLUNA16.py", I have added fold9 csv for test (/luna_detector/labels/luna_test.csv), you can directly run noduleCADEvaluationLUNA16.py to generate the results. The results should match the one that I uploaded.

I am not sure if that's the bug causing low performance, but you should be able to generate the same figure as I uploaded after I fix that bug.

update (mis-clicked close instead, just reopened this):
The missing nodules in file "nodulesWithoutCandidate_predanno0.3.txt." should be:

237,None,56.58885682,-67.46153204,-77.34666348,3.270466947,-1
612,None,-6.607170093,22.55937329,-143.7929641,9.484890340,-1
612,None,116.8024039,-1.291850522,-197.5054168,4.666322736,-1
612,None,119.2088976,-11.4328236,-208.2932951,6.853377495,-1
612,None,111.5336493,-37.25625083,-238.8281758,5.772283337,-1
612,None,95.99601184,-23.33441995,-157.7220192,4.835148932,-1
