### ISSUE TITLE
Question about FROC score

### ISSUE THREAD

**Issue by kacel33** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#43]
I made changes to "noduleCADEvaluationLUNA16.py", added "luna_test.csv", and checked the "predanno0.3.csv" result that you uploaded to the GitHub repository. However, the resulting output differs from what is mentioned in the paper.

Thank you for getting back to me.

![froc_predanno0 3](https://user-images.githubusercontent.com/60708119/219988411-35b6c8ec-420c-4724-8b46-750c571ae057.png)

After running the code again, I got the following result.
![froc_predanno0 3](https://user-images.githubusercontent.com/60708119/219992486-0ef2d7f9-ca6b-4128-a8e0-6611b691c690.png)

**Comment by kacel33** [comment]
The problem has been fixed.

**Comment by Pang-b0** [comment]
Hi, I have encountered this problem, and I want to ask you how to repair "noduleCADEvaluationLUNA16.py", and I have some doubts about how to use FROCeval.py Can you show me what paths to fill in annotations_filename, annotations_excluded_filename and seriesuids_filename?
