### ISSUE TITLE
checkpoint

### ISSUE THREAD

**Issue by thestars-maker** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#44]
Please tell me where the 177.ckpt file is, and how the project's configuration environment is roughly, please teach me

**Comment by ymli39** [comment]
The file name '177.ckpt' is only an example of the loading format. To load my uploaded pretrained weights, please use the file '207.ckpt'.

This project was completed four years ago, and although I do not recall the specific configurations required, I believe it included all the basic functions.
