### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by SajidDeltax** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#49]
HI @ymli39, 
I am trying to reproduce the result. Please share the installation guide or the Python version. 
Thank you for your efforts.

**Comment by ymli39** [comment]
Hi I don't recall exact version number but I used Python 3.

**Comment by SajidDeltax** [comment]
Thank you for the response. Great work! I have reproduced the results.

**Comment by ymli39** [comment]
Great to know, thx for your support and good luck to your research!
