### ISSUE TITLE
Dataloader has inputs other than size 128. 

### ISSUE THREAD

**Issue by gauthamnandakumar** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#8]
Hey,
When I load my dataloader, the input coming in is with image size other than 128. 
![image](https://user-images.githubusercontent.com/29469456/63827253-703a6880-c930-11e9-8235-056bc9556b7c.png)

And for executing your step1.py file, to save the mask I followed the following code : 
out_folder = 'E:\\LUNA Dataset\\mask\\'
for idx,i in enumerate(target_filenames):
    filename = i.split('\\')[-1]
    print(idx,i)
    case_pixels, bw1, bw2, spacing, origin = step1_python(i)
    bw = bw1*3+bw2*4
    bw = sitk.GetImageFromArray(np.uint8(bw))
    bw.SetSpacing(spacing)
    bw.SetOrigin(origin)
    sitk.WriteImage(bw,out_folder+filename, True) 

Am I right?

**Comment by ymli39** [comment]
Is this because your mask or original image has size smaller than 128?
