### ISSUE TITLE
Idcs 

### ISSUE THREAD

**Issue by Shrutika994** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#9]
![new newe](https://user-images.githubusercontent.com/38447988/64403275-e702fe80-d0b2-11e9-8c7e-1605e238cb87.PNG)
Hello, can you please share how these labels are only picked up for training.

**Comment by ymli39** [comment]
I followed previous state-of-the-art work to chose the labels in order to have a consistent comparison.

**Comment by Shrutika994** [comment]
Did you by any chance faced any difficulty while downloading the luna16 dataset. were all the the raw and mhd files were present for you?

**Comment by ymli39** [comment]
yes no problem for me to download LUNA16 dataset from their website.
